install.packages("survival")
install.packages("survminer")
library(survival)
library(survminer)
library(ggplot2)
library(survMisc)
data <- read_excel("C:/Users/chloe/Desktop/hw4 data.xlsx")
colnames(data)<-c("time","status","trt")
fit <- survfit(Surv(time, status)~1, data=data)
summary(fit)
ggsurvplot(fit, color ="#2E9FDF",data)
sfit <- survfit(Surv(time, status)~factor(trt), data=data)
summary(sfit)
ggsurvplot(sfit, data=data,legend = "bottom", 
           legend.title = "Group",
           legend.labs = c("A", "B"))
survdiff(Surv(time, status) ~ factor(trt), data, rho = 0)
1-pchisq(2.4,1)
survdiff(Surv(time, status) ~ factor(trt), data, rho = 1)
1-pchisq(3.8,1)
